export const photos = [
  {
    src: "/images/gallery/mix/01.webp",
    width: 4,
    height: 3,
    title: "Naše první pusa",
  },
  {
    src: "/images/gallery/mix/02.webp",
    width: 4,
    height: 5,
    title:
      "Kvůli tomuhle jsme se poznali. Svatba Pavlínky a Kamila Regnerových",
  },
  {
    src: "/images/gallery/mix/04.webp",
    width: 4,
    height: 6,
    title: "",
  },
  {
    src: "/images/gallery/mix/05.webp",
    width: 4,
    height: 2.67,
    title: "",
  },
  {
    src: "/images/gallery/mix/06.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/07.webp",
    width: 4,
    height: 8.66,
    title: "",
  },
  {
    src: "/images/gallery/mix/08.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/09.webp",
    width: 4,
    height: 8.66,
    title: "",
  },
  {
    src: "/images/gallery/mix/10.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/11.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/12.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/13.webp",
    width: 4,
    height: 8.66,
    title: "",
  },
  {
    src: "/images/gallery/mix/14.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/15.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/16.webp",
    width: 4,
    height: 3,
    title: "",
  },
  {
    src: "/images/gallery/mix/17.webp",
    width: 4,
    height: 3.13,
    title: "",
  },
  {
    src: "/images/gallery/mix/18.webp",
    width: 4,
    height: 2.64,
    title: "",
  },
  {
    src: "/images/gallery/mix/19.webp",
    width: 4,
    height: 5.33,
    title: "",
  },
  {
    src: "/images/gallery/mix/20.webp",
    width: 4,
    height: 3,
    title: "",
  },
  {
    src: "/images/gallery/mix/21.webp",
    width: 4,
    height: 5.78,
    title: "",
  },
  {
    src: "/images/gallery/mix/22.webp",
    width: 4,
    height: 7.12,
    title: "",
  },
  {
    src: "/images/gallery/mix/24.webp",
    width: 4,
    height: 2.65,
    title: "",
  },
  {
    src: "/images/gallery/mix/25.webp",
    width: 4,
    height: 3,
    title: "",
  },
  {
    src: "/images/gallery/mix/26.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/mix/27.webp",
    width: 4,
    height: 5.33,
    title: "",
  },
  {
    src: "/images/gallery/mix/28.webp",
    width: 4,
    height: 2.28,
    title: "",
  },
  {
    src: "/images/gallery/mix/29.webp",
    width: 4,
    height: 2.48,
    title: "",
  },
  {
    src: "/images/gallery/mix/30.webp",
    width: 4,
    height: 3,
    title: "",
  },
  {
    src: "/images/gallery/mix/31.webp",
    width: 4,
    height: 5.35,
    title: "",
  },
  {
    src: "/images/gallery/mix/32.webp",
    width: 4,
    height: 3,
    title: "",
  },
  {
    src: "/images/gallery/mix/33.webp",
    width: 4,
    height: 2.67,
    title: "",
  },
  {
    src: "/images/gallery/mix/34.webp",
    width: 4,
    height: 5.35,
    title: "",
  },
  {
    src: "/images/gallery/mix/35.webp",
    width: 4,
    height: 4,
    title: "",
  },
  {
    src: "/images/gallery/mix/36.webp",
    width: 4,
    height: 5.34,
    title: "",
  },
  {
    src: "/images/gallery/01.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/02.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/03.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/04.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/05.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/06.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/07.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/08.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/09.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/10.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/11.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/12.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/13.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/14.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/15.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/16.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/17.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/18.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/19.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/20.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/21.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/22.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/23.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
  {
    src: "/images/gallery/24.webp",
    width: 4,
    height: 2.67,
    title: "Svatební focení",
  },
];
